version: '3.8'

services:
  traefik:
    image: "traefik:v2.9"
    restart: always
    command:
      - "--providers.docker=true"
      - "--configFile=/etc/traefik/traefik.yml"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    volumes:
      - "./data/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  iron_nest:
    build: .
    network_mode: "host"
    volumes:
      - "./data/app/:/app/data/"
      - "traefik.yaml:/etc/traefik/traefik.yml"
      - "traefik-config.yml:/etc/traefik/traefik-config.yml"